.PHONY: all clean

F2PY = f2py3
F2PY_FLAGS = --quiet
#F2PY_FLAGS +=-DF2PY_REPORT_ON_ARRAY_COPY=1
#F2PY_FLAGS +=--noarch --f90flags='${ARCHFLAGS}'

MODULE=lowtran

SOURCES = lowtran7.f

all: ${MODULE}.so

${MODULE}.so: ${SOURCES}
	${F2PY} ${F2PY_FLAGS} -c $^ -m ${MODULE}

clean:
	${RM} ${MODULE}.so
