if(CMAKE_Fortran_COMPILER_ID STREQUAL GNU)
# mtune instead of march for better CPU compatibility
  add_compile_options(-mtune=native)
  set(old_flags -std=legacy -w)
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL Intel)
  if(WIN32)
    add_compile_options(/arch:native)
    set(old_flags /w)
  else()
    add_compile_options(-march=native)
    set(old_flags -w)
  endif()
endif()
